language: ruby
rvm:
- 2.3.4
sudo: false
dist: precise
services: postgresql
bundler_args: "--without production development --binstubs --jobs=3 --retry=3"
before_install: gem install bundler -v 1.11.2
cache: bundler
env:
  global:
  - SECRET_KEY_BASE=f152b24044a9dd45656eea8a30f7d7df367497dc4fb53e563425db71c43dc0f959d4d6e62ed54811c6b925db0237a1e16ea9ce1103019ac329660afe40634ead
  - DEVISE_PEPPER=c9437c0aac74ceb06f8d49b1cd1f360d49cc43446a33d5d7e02016038e925c99d6f92afee5ea8b547702c05b5f36ac2cd532516b3e04dac617a430a9cc403472
  - DATABASE_USERNAME=postgres
  - DATABASE_PASSWORD=
  - SITE_NAME=TravisTekkedOutDNDTools
script:
- bundle exec rake rubocop
- psql -c 'create database tekkedout_dnd_tools_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake spec
